#!/bin/sh

fatal()
{
  echo "cc-compile: fatal: $1" 1>&2
  exit 1
}

if [ $# -lt 1 ]
then
  echo "cc-compile: usage: [@dir] source" 1>&2
  exit 1
fi

#
# check if new base dir was specified
#

BASE_DIR="."
if [ $# -gt 1 ]
then
  echo "$1" | grep '^@' >/dev/null
  if [ $? -eq 0 ]
  then
    BASE_DIR=`echo "$1" | sed 's/^@//g'`
    shift
  fi
fi

#
# Extract base name of given source file.
#

out=`echo "$1" | awk -F. '{print $1}'`
src="$1"
shift

#
# Assume source is being cross compiled if there is a cross-compiler
# defined.
#

if [ -f "${BASE_DIR}/conf-x-cc" ]
then
  CC=`head -n 1 "${BASE_DIR}/conf-x-cc"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-x-cc"
  fi
  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-x-systype"
  fi
  CCTYPE=`head -n 1 "${BASE_DIR}/conf-x-cctype"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-x-cctype"
  fi
  CFLAGS="${CFLAGS} `head -n 1 "${BASE_DIR}/conf-x-cflags" 2>/dev/null`"
else
  CC=`head -n 1 "${BASE_DIR}/conf-cc"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-cc"
  fi
  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-systype"
  fi
  CCTYPE=`head -n 1 "${BASE_DIR}/conf-cctype"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-cctype"
  fi
fi

CFLAGS="${CFLAGS} `head -n 1 ${BASE_DIR}/conf-cflags 2>/dev/null`"

#
# Read global flag file list, if present.
#

if [ -f "${BASE_DIR}/conf-ccfflist" ]
then
  for f in `cat "${BASE_DIR}/conf-ccfflist"`
  do
    FLAGS=`cat $f 2>/dev/null`
    CFLAGS="${CFLAGS} ${FLAGS}"
  done
fi

#
# Read local flag file list, if present.
#

if [ -f "${out}.iff" ]
then
  for f in `cat "${out}.iff"`
  do
    targ="`dirname $out`/`dirname $f`/`basename $f`"
    FLAGS="`cat $targ 2>/dev/null`"
    CFLAGS="${CFLAGS} ${FLAGS}"
  done
fi

#
# compensate for any compiler bugs
#

case ${SYSTYPE} in
  DARWIN)
    case ${CCTYPE} in
      GCC)
        CFLAGS="${CFLAGS} -fno-common"  # darwin linker bug workaround
        ;;
      *)
        ;;
    esac
    ;;
  *)
    ;;
esac

exec ${CC} -o ${out}.o -c ${src} ${1+"$@"} ${CFLAGS}
