#!/bin/sh

fatal()
{
  echo "cc-slib: fatal: $1" 1>&2
  exit 1
}

if [ $# -lt 2 ]
then
  echo "cc-slib: usage: [@dir] basename objects ..." 1>&2
  exit 1
fi

#
# check if base directory was specified
#

BASE_DIR="."
echo "$1" | grep '^@' 2>&1 >/dev/null
if [ $? -eq 0 ]
then
  BASE_DIR=`echo $1 | sed 's/^@//g'`
  shift
fi

SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
if [ $? -ne 0 ]
then
  fatal "could not read ${BASE_DIR}/conf-systype"
fi

AR="ar cr"
if [ -f "${BASE_DIR}/conf-ar" ]
then
  AR=`head -n 1 "${BASE_DIR}/conf-ar"`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-ar"
  fi
fi

RANLIB="ranlib"
if [ -f ${BASE_DIR}/conf-ranlib ]
then
  RANLIB=`head -n 1 ${BASE_DIR}/conf-ranlib`
  if [ $? -ne 0 ]
  then
    fatal "could not read ${BASE_DIR}/conf-ranlib"
  fi
fi

main="$1"
shift

rm -f "${main}".a
${AR} "${main}".a ${1+"$@"}

case "${SYS_TYPE}" in
  SUNOS) ;;
  SCO_OPENSERVER) ;;
  UNIXWARE) ;;
  IRIX) ;;
  DG_UX) ;;
  UNIXWARE) ;;
  CRAY_UNICOS) ;;
  VMS) ;;
  *)
    ${RANLIB} "$main.a"
    ;;
esac
