#!/bin/sh

temp_f="$1"
temp_sys="$2"

args=""
path="${SYSDEP_STDINC}"
file="lua.h"

FLAGS=`${SYSDEP_TRY_MANUAL} "${file}" "${path}" "-I" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo "${FLAGS} -DHAVE_LUA " >> "${temp_f}"
  echo "lua-flags: ${FLAGS} -DHAVE_LUA " >> "${temp_sys}"
  exit 0
fi

#
# Lua uses versioned directories.
#

for dir in ${path}
do
  maybe_dirs=`ls ${dir} | grep lua`
  for dir_ext in ${maybe_dirs}
  do
    if [ -f "${dir}/${dir_ext}/${file}" ]
    then
      echo "-I${dir}/${dir_ext} -DHAVE_LUA " >> "${temp_f}"
      echo "lua-flags: -I${dir}/${dir_ext} -DHAVE_LUA " >> "${temp_sys}"
      exit 0
    fi
  done
done

${SYSDEP_ERROR} "manual/custom search failed"
exit 0 
