#!/bin/sh

temp_f="$1"
temp_sys="$2"

args=""
path="${SYSDEP_STDLIB}"
file="liblua.a"

FLAGS=`${SYSDEP_TRY_MANUAL} "${file}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  echo "${FLAGS} -llua " >> "${temp_f}"
  echo "lua-libs-S: ${FLAGS} -llua " >> "${temp_sys}"
  exit 0
fi

#
# Lua uses versioned directories.
#

for dir in ${path}
do
  maybe_dirs=`ls ${dir} | grep lua`
  for dir_ext in ${maybe_dirs}
  do
    maybe_libs=`ls "${dir}/${dir_ext}" | grep 'liblua[0-9.]*\.a'`
    for lib_ext in ${maybe_libs}
    do
      if [ -f "${dir}/${dir_ext}/${lib_ext}" ]
      then
        ${SYSDEP_INFO} "using ${dir}/${dir_ext}/${lib_ext}"
        echo "${dir}/${dir_ext}/${lib_ext} " >> "${temp_f}"
        echo "libs-lua-S: ${dir}/${dir_ext}/${lib_ext} " >> "${temp_sys}"
        exit 0
      fi
    done
  done
done

${SYSDEP_ERROR} "manual/custom search failed"
exit 0 
