#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

temp_f="$1"
temp_sys="$2"

args=""
path="${SYSDEP_STDLIB}"
file="liblua.a"

FLAGS=`${SYSDEP_TRY_MANUAL} "${file}" "${path}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  ${SYSDEP_UTIL_ECHO} "${FLAGS} -llua " >> "${temp_f}"
  ${SYSDEP_UTIL_ECHO} "lua-libs-S: ${FLAGS} -llua " >> "${temp_sys}"
  ${SYSDEP_UTIL_EXIT} 0
fi

#
# Lua distributors are clearly insane.
#

case ${SYSDEP_OS} in
  SYSDEP_OS_FREEBSD)
    for basedir in ${path}
    do
      lua_dirs=`ls ${basedir} 2>/dev/null | ${SYSDEP_UTIL_GREP} 'lua[0-9]*$' 2>/dev/null`
      for dir in ${lua_dirs}
      do
        if [ -f "${basedir}/${dir}/${file}" ]
        then
          ${SYSDEP_UTIL_ECHO} "${basedir}/${dir}/${file} " >> "${temp_f}"
          ${SYSDEP_UTIL_ECHO} "lua-libs-S: ${basedir}/${dir}/${file} " >> "${temp_sys}"
          ${SYSDEP_UTIL_EXIT} 0
        fi
      done
    done
    ;;
  SYSDEP_OS_LINUX)
    for basedir in ${path}
    do
      lua_libs=`ls ${basedir} 2>/dev/null | ${SYSDEP_UTIL_GREP} 'liblua[0-9]*\.[0-9]*\.a' 2>/dev/null`
      for lib in ${lua_libs}
      do
        if [ -f "${basedir}/${lib}" ]
        then
          ${SYSDEP_UTIL_ECHO} "${basedir}/${lib} -ldl " >> "${temp_f}"
          ${SYSDEP_UTIL_ECHO} "lua-libs-S: ${basedir}/${lib} -ldl " >> "${temp_sys}"
          ${SYSDEP_UTIL_EXIT} 0
        fi
      done
    done
    ;;
esac

SYSDEP_FATAL "manual/custom search failed"
